service: fetch-file-and-store-in-s3

frameworkVersion: ">=1.1.0"

custom:
  bucket: gani-sls-image-upload

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}

resources:
  Resources:
    BUCKET:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
